---
title: "Chunyun Ma's CV"
author: Chunyun Ma
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/173s9yLVH3Dl23ws9FxG06qU5p8SBvb15lQUWVOutI0I/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _chunyunma.me/about-me/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/chunyunma/resume/raw/master/resume.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**datadrivencv**](http://nickstrayer.me/datadrivencv/index.html). 

The source code is available [on github.com/chunyunma/resume](https://github.com/chunyunma/resume).

Last updated on `r Sys.Date()`.



Main
================================================================================

Chunyun Ma {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```





<!-- Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_section('research_positions') -->
<!-- ``` -->



<!-- Industry Experience {data-icon=suitcase} -->
<!-- -------------------------------------------------------------------------------- -->
<!--  -->
<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('industy_experience_aside') -->
<!-- ``` -->
<!-- ::: -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_section('industry_positions') -->
<!-- ``` -->

<!-- These breaks just force a new page so section doesnt get cut off -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

Selected Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('teaching_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('teaching')
```

Selected Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_experience')
```


<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->
<!--  -->
<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->



<!-- Selected Press (About)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_section('about_me_press') -->
<!-- ``` -->
<!--  -->
<!--  -->
<!-- <br> -->
<!-- <br> -->
<!--  -->

<!-- Selected Press (By)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_section('by_me_press') -->
<!-- ``` -->



Selected Communication Experience {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('publication')
```

<!--  -->
<!--  -->
<!-- ```{r} -->
<!-- CV %<>% print_links() -->
<!-- ``` -->


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```
